plugins {
    id 'com.android.application'
}

android {
    namespace 'org.alee.wallpaper.multipicture.dnt'
    compileSdk 34

    defaultConfig {
        applicationId 'org.alee.wallpaper.multipicture.dnt'
        minSdk 7
        targetSdk 34
        versionCode 48
        versionName '0.6.12'
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            res.srcDirs = ['res']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation project(':')
}
